### ISSUE TITLE
More Blue in the Placeholder example

### ISSUE THREAD

**Issue by robzolkos** [shipearlyshipoften/shipearlyshipoften.com#3]
Maybe with a little pop...

This is in reference #2

**Comment by jaymiejones86** [comment]
Like this? http://codepen.io/jaymiejones86/pen/XbjEoQ

**Comment by robzolkos** [comment]
Yep perfect.

**Comment by jaymiejones86** [comment]
Changed it to a gradient.

**Comment by robzolkos** [comment]
Should the gradient go the other way, in case of left handed people? @jaymiejones86 ?

**Comment by jaymiejones86** [comment]
Meh for the time being, it will change once I launch the manifesto
![](http://www.davidfeldmanblog.com/wp-content/uploads/2014/07/flanders.jpg)
